#!/bin/bash

base_url=http://localhost:9021/v1
workers=5
max_frames=400
temperature=0.9
history_num=2
action_chunk_len=1
instruction_type="recipe"
model_name_or_path="/public/models/JarvisVLA-qwen2-vl-7b"
model_local_path="JarvisVLA-qwen2-vl-7b" #"mc-vla-qwen2-vl-7b-250311-A800-c32-e1-b16-a1"

tasks=(
   craft/netherite_ingot
    craft/oak_fence_gate
    craft/lime_concrete_powder
    craft/glass_bottle
    craft/end_stone_brick_wall
    craft/smooth_red_sandstone_slab
    craft/magenta_wool
    craft/gold_nugget
    craft/stone_pressure_plate
    craft/bone_block
    craft/jack_o_lantern
    craft/chain
    craft/acacia_wood
    craft/purple_bed
    craft/light_gray_concrete_powder
    craft/bucket
    craft/hopper_minecart
    craft/green_carpet
    craft/bow
    craft/dried_kelp
    craft/jungle_planks
    craft/smooth_quartz_stairs
    craft/chiseled_polished_blackstone
    craft/acacia_door
    craft/pumpkin_pie
    craft/nether_brick_stairs
    craft/diamond
    craft/red_wool
    craft/stone_brick_stairs
    craft/crafting_table
    craft/dark_oak_fence_gate
    craft/white_dye
    craft/jungle_boat
    craft/melon_seeds
    craft/diamond_boots
    craft/blue_bed
    craft/magenta_stained_glass_pane
    craft/powered_rail
    craft/oak_slab
    craft/iron_chestplate
    craft/polished_blackstone_pressure_plate
    craft/white_concrete_powder
    craft/brown_dye
    craft/jungle_wood
    craft/stone_stairs
    craft/chest_minecart
    craft/gray_bed
    craft/white_stained_glass_pane
    craft/cookie
    craft/green_stained_glass_pane
    craft/loom
    craft/observer
    craft/yellow_wool
    craft/diamond_sword
    craft/red_carpet
    craft/gold_block
    craft/pink_banner
    craft/warped_stairs
    craft/minecart
    craft/polished_blackstone_slab
    craft/purple_concrete_powder
    craft/spruce_button
    craft/cartography_table
    craft/wooden_sword
    craft/flint_and_steel
    craft/purpur_slab
    craft/spruce_boat
    craft/dark_oak_door
    craft/diorite_slab
    craft/gray_wool
    craft/oak_door
    craft/orange_concrete_powder
    craft/cut_sandstone_slab
    craft/creeper_banner_pattern
    craft/red_nether_bricks
    craft/polished_blackstone_bricks
    craft/granite_stairs
    craft/crimson_pressure_plate
    craft/lectern
    craft/gray_dye
    craft/stone_axe
    craft/purpur_block
    craft/emerald_block
    craft/jungle_fence_gate
    craft/white_terracotta
    craft/pink_stained_glass
    craft/warped_sign
    craft/warped_trapdoor
    craft/wheat
    craft/brown_bed
    craft/brick_wall
    craft/orange_bed
    craft/lime_wool
    craft/mossy_stone_brick_stairs
    craft/torch
    craft/furnace_minecart
    craft/acacia_boat
    craft/rabbit_stew
    craft/oak_trapdoor
    craft/leather_leggings
    craft/emerald
    craft/prismarine_slab
    craft/white_wool
    craft/painting
    craft/golden_hoe
    craft/campfire
    craft/chiseled_sandstone
    craft/bookshelf
    craft/polished_diorite
    craft/spruce_fence_gate
    craft/compass
    craft/glowstone
    craft/acacia_stairs
    craft/prismarine_brick_slab
    craft/wooden_shovel
    craft/crimson_fence
    craft/glistering_melon_slice
    craft/green_bed
    craft/yellow_concrete_powder
    craft/stone_brick_slab
    craft/crimson_slab
    craft/anvil
    craft/cauldron
    craft/jungle_pressure_plate
    craft/snow
    craft/yellow_carpet
    craft/polished_diorite_stairs
    craft/dark_oak_slab
    craft/quartz_bricks
    craft/black_stained_glass_pane
    craft/mojang_banner_pattern
    craft/dark_prismarine_stairs
    craft/book
    craft/magenta_dye
    craft/light_gray_stained_glass_pane
    craft/lime_bed
    craft/flower_pot
    craft/leather_chestplate
    craft/light_blue_concrete_powder
    craft/cut_red_sandstone_slab
    craft/blue_terracotta
    craft/glass_pane
    craft/beacon
    craft/dark_oak_trapdoor
    craft/dropper
    craft/black_concrete_powder
    craft/polished_blackstone_button
    craft/oak_sign
    craft/iron_trapdoor
    craft/end_rod
    craft/green_stained_glass
    craft/wooden_hoe
    craft/acacia_pressure_plate
    craft/mossy_cobblestone_wall
    craft/light_blue_stained_glass_pane
    craft/jukebox
    craft/red_bed
    craft/iron_shovel
    craft/wooden_axe
    craft/pink_terracotta
    craft/pink_dye
    craft/stripped_dark_oak_wood
    craft/nether_brick_fence
    craft/cyan_stained_glass
    craft/crimson_button
    craft/redstone_lamp
    craft/jungle_button
    craft/leather_boots
    craft/brown_stained_glass_pane
    craft/chest
    craft/light_weighted_pressure_plate
    craft/brick_slab
    craft/pink_wool
    craft/magenta_banner
    craft/stone_slab
    craft/diorite_wall
    craft/granite
    craft/snow_block
    craft/prismarine_stairs
    craft/stripped_birch_wood
    craft/pink_concrete_powder
    craft/stripped_spruce_wood
    craft/cobblestone_slab
    craft/acacia_slab
    craft/granite_slab
    craft/respawn_anchor
    craft/tnt
    craft/skull_banner_pattern
    craft/paper
    craft/spruce_wood
    craft/spruce_pressure_plate
    craft/blue_stained_glass_pane
    craft/light_blue_dye
    craft/comparator
    craft/light_gray_bed
    craft/red_concrete_powder
    craft/daylight_detector
    craft/rail
    craft/crimson_trapdoor
    craft/dark_oak_sign
    craft/oak_stairs
    craft/brown_carpet
    craft/green_banner
    craft/writable_book
    craft/fletching_table
    craft/smooth_stone_slab
    craft/magenta_terracotta
    craft/lead
    craft/dark_prismarine_slab
    craft/crimson_sign
    craft/black_terracotta
    craft/light_blue_stained_glass
    craft/golden_shovel
    craft/bone_meal
    craft/orange_terracotta
    craft/brown_banner
    craft/dark_oak_wood
    craft/gray_banner
    craft/cyan_dye
    craft/craft_crafting_table
    craft/cut_red_sandstone
    craft/sandstone_slab
    craft/diamond_chestplate
    craft/redstone
    craft/dark_oak_button
    craft/flower_banner_pattern
    craft/black_dye
    craft/cyan_stained_glass_pane
    craft/stonecutter
    craft/fire_charge
    craft/blue_carpet
    craft/iron_hoe
    craft/mossy_cobblestone_stairs
    craft/lime_dye
    craft/birch_door
    craft/birch_sign
    craft/end_stone_bricks
    craft/trapped_chest
    craft/blackstone_wall
    craft/purple_wool
    craft/golden_apple
    craft/purple_stained_glass_pane
    craft/sticky_piston
    craft/white_carpet
    craft/red_stained_glass
    craft/stone_hoe
    craft/enchanting_table
    craft/polished_andesite
    craft/blue_dye
    craft/pink_stained_glass_pane
    craft/stick
    craft/black_bed
    craft/end_stone_brick_stairs
    craft/warped_fungus_on_a_stick
    craft/clay
    craft/sandstone_wall
    craft/light_blue_bed
    craft/acacia_button
    craft/prismarine
    craft/jungle_trapdoor
    craft/acacia_fence_gate
    craft/piston
    craft/dark_oak_stairs
    craft/cyan_carpet
    craft/light_blue_banner
    craft/nether_bricks
    craft/packed_ice
    craft/oak_button
    craft/birch_pressure_plate
    craft/oak_pressure_plate
    craft/grindstone
    craft/stone_bricks
    craft/yellow_stained_glass
    craft/stone_brick_wall
    craft/dispenser
    craft/pumpkin_seeds
    craft/golden_boots
    craft/andesite_stairs
    craft/polished_andesite_slab
    craft/dark_prismarine
    craft/iron_leggings
    craft/dark_oak_planks
    craft/light_gray_stained_glass
    craft/mossy_stone_bricks
    craft/lapis_block
    craft/lodestone
    craft/light_gray_terracotta
    craft/hopper
    craft/lime_stained_glass_pane
    craft/smooth_red_sandstone_stairs
    craft/quartz_pillar
    craft/brown_concrete_powder
    craft/melon
    craft/light_gray_wool
    craft/blue_banner
    craft/purpur_stairs
    craft/purpur_pillar
    craft/nether_wart_block
    craft/jungle_sign
    craft/polished_blackstone_brick_slab
    craft/orange_dye
    craft/coal_block
    craft/shield
    craft/magenta_bed
    craft/polished_granite_slab
    craft/gray_concrete_powder
    craft/cyan_concrete_powder
    craft/heavy_weighted_pressure_plate
    craft/iron_bars
    craft/ender_eye
    craft/sea_lantern
    craft/cyan_wool
    craft/iron_helmet
    craft/birch_stairs
    craft/oak_fence
    craft/granite_wall
    craft/dried_kelp_block
    craft/yellow_dye
    craft/iron_block
    craft/spruce_sign
    craft/magenta_carpet
    craft/leather_helmet
    craft/yellow_banner
    craft/yellow_bed
    craft/stone_shovel
    craft/black_banner
    craft/birch_slab
    craft/blackstone_slab
    craft/tnt_minecart
    craft/blue_stained_glass
    craft/polished_blackstone_wall
    craft/note_block
    craft/slime_block
    craft/tripwire_hook
    craft/spruce_slab
    craft/beetroot_soup
    craft/prismarine_wall
    craft/blue_wool
    craft/magenta_concrete_powder
    craft/crimson_door
    craft/diamond_helmet
    craft/yellow_terracotta
    craft/shulker_box
    craft/red_terracotta
    craft/smoker
    craft/acacia_sign
    craft/crimson_stairs
    craft/red_banner
    craft/orange_wool
    craft/blackstone_stairs
    craft/lantern
    craft/acacia_planks
    craft/spruce_door
    craft/quartz_block
    craft/spruce_planks
    craft/red_nether_brick_wall
    craft/lever
    craft/pink_bed
    craft/oak_wood
    craft/birch_trapdoor
    craft/warped_door
    craft/ender_chest
    craft/warped_fence_gate
    craft/red_dye
    craft/redstone_block
    craft/iron_nugget
    craft/fishing_rod
    craft/light_gray_banner
    craft/oak_boat
    craft/brewing_stand
    craft/beehive
    craft/conduit
    craft/black_carpet
    craft/red_nether_brick_slab
    craft/magma_block
    craft/mossy_cobblestone_slab
    craft/stripped_jungle_wood
    craft/gray_stained_glass_pane
    craft/shears
    craft/diorite_stairs
    craft/map
    craft/yellow_stained_glass_pane
    craft/red_sandstone_wall
    craft/blast_furnace
    craft/gray_stained_glass
    craft/chiseled_red_sandstone
    craft/warped_fence
    craft/spruce_fence
    craft/jungle_fence
    craft/green_concrete_powder
    craft/soul_torch
    craft/white_banner
    craft/diamond_shovel
    craft/composter
    craft/orange_stained_glass_pane
    craft/gold_ingot
    craft/nether_brick_slab
    craft/cyan_banner
    craft/prismarine_bricks
    craft/item_frame
    craft/redstone_torch
    craft/honey_bottle
    craft/activator_rail
    craft/blue_concrete_powder
    craft/purple_dye
    craft/magenta_stained_glass
    craft/polished_basalt
    craft/polished_blackstone
    craft/prismarine_brick_stairs
    craft/green_wool
    craft/light_blue_wool
    craft/stone_pickaxe
    craft/smooth_quartz_slab
    craft/slime_ball
    craft/red_stained_glass_pane
    craft/lime_terracotta
    craft/andesite_wall
    craft/diamond_leggings
    craft/black_wool
    craft/target
    craft/iron_boots
    craft/iron_pickaxe
    craft/polished_blackstone_stairs
    craft/soul_campfire
    craft/crimson_hyphae
    craft/iron_axe
    craft/soul_lantern
    craft/golden_axe
    craft/warped_slab
    craft/cyan_bed
    craft/blue_ice
    craft/detector_rail
    craft/stone_button
    craft/polished_blackstone_brick_stairs
    craft/sandstone
    craft/diamond_hoe
    craft/stripped_crimson_hyphae
    craft/cobblestone_wall
    craft/ladder
    craft/jungle_door
    craft/birch_fence
    craft/stripped_warped_hyphae
    craft/purple_banner
    craft/scaffolding
    craft/birch_fence_gate
    craft/warped_hyphae
    craft/bricks
    craft/red_sandstone_slab
    craft/arrow
    craft/light_blue_terracotta
    craft/green_terracotta
    craft/polished_granite_stairs
    craft/polished_blackstone_brick_wall
    craft/iron_sword
    craft/cobblestone_stairs
    craft/sugar
    craft/chiseled_stone_bricks
    craft/gray_carpet
    craft/hay_block
    craft/mossy_stone_brick_slab
    craft/oak_planks
    craft/coal
    craft/golden_chestplate
    craft/andesite
    craft/orange_banner
    craft/clock
    craft/bread
    craft/honey_block
    craft/light_blue_carpet
    craft/end_stone_brick_slab
    craft/golden_sword
    craft/mossy_stone_brick_wall
    craft/magma_cream
    craft/birch_button
    craft/dark_oak_pressure_plate
    craft/blaze_powder
    craft/stripped_acacia_wood
    craft/nether_brick_wall
    craft/cut_sandstone
    craft/sandstone_stairs
    craft/armor_stand
    craft/chiseled_nether_bricks
    craft/repeater
    craft/spruce_trapdoor
    craft/warped_planks
    craft/netherite_block
    craft/barrel
    craft/lapis_lazuli
    craft/orange_carpet
    craft/lime_stained_glass
    craft/jungle_slab
    craft/golden_pickaxe
    craft/spectral_arrow
    craft/quartz_slab
    craft/light_gray_dye
    craft/quartz_stairs
    craft/honeycomb_block
    craft/brown_terracotta
    craft/chiseled_quartz_block
    craft/lime_carpet
    craft/white_stained_glass
    craft/crimson_planks
    craft/purple_terracotta
    craft/diamond_block
    craft/iron_ingot
    craft/diamond_axe
    craft/fermented_spider_eye
    craft/stripped_oak_wood
    craft/birch_wood
    craft/white_bed
    craft/bowl
    craft/lime_banner
    craft/jungle_stairs
    craft/red_sandstone
    craft/black_stained_glass
    craft/mossy_cobblestone
    craft/orange_stained_glass
    craft/diorite
    craft/polished_diorite_slab
    craft/stone_sword
    craft/warped_pressure_plate
    craft/light_gray_carpet
    craft/cake
    craft/golden_leggings
    craft/brown_stained_glass
    craft/dark_oak_fence
    craft/golden_helmet
    craft/crimson_fence_gate
    craft/brown_wool
    craft/red_sandstone_stairs
    craft/purple_carpet
    craft/acacia_trapdoor
    craft/brick_stairs
    craft/polished_andesite_stairs
    craft/mushroom_stew
    craft/polished_granite
    craft/iron_door
    craft/pink_carpet
    craft/birch_planks
    craft/furnace
    craft/leather_horse_armor
    craft/turtle_helmet
    craft/coarse_dirt
    craft/purple_stained_glass
    craft/crossbow
    craft/smooth_sandstone_stairs
    craft/warped_button
    craft/leather
    craft/dark_oak_boat
    craft/gray_terracotta
    craft/end_crystal
    smelt/gold_nugget
    smelt/cooked_cod
    smelt/dried_kelp
    smelt/light_gray_glazed_terracotta
    smelt/diamond
    smelt/brick
    smelt/smooth_red_sandstone
    smelt/cooked_beef
    smelt/light_blue_glazed_terracotta
    smelt/pink_glazed_terracotta
    smelt/purple_glazed_terracotta
    smelt/green_dye
    smelt/cracked_nether_bricks
    smelt/quartz
    smelt/white_glazed_terracotta
    smelt/cyan_glazed_terracotta
    smelt/orange_glazed_terracotta
    smelt/cooked_rabbit
    smelt/green_glazed_terracotta
    smelt/gray_glazed_terracotta
    smelt/cooked_salmon
    smelt/blue_glazed_terracotta
    smelt/baked_potato
    smelt/lime_glazed_terracotta
    smelt/redstone
    smelt/lime_dye
    smelt/charcoal
    smelt/sponge
    smelt/nether_brick
    smelt/iron_nugget
    smelt/smooth_quartz
    smelt/cooked_porkchop
    smelt/smooth_stone
    smelt/gold_ingot
    smelt/magenta_glazed_terracotta
    smelt/netherite_scrap
    smelt/cracked_polished_blackstone_bricks
    smelt/cooked_chicken
    smelt/coal
    smelt/lapis_lazuli
    smelt/terracotta
    smelt/iron_ingot
    smelt/smooth_sandstone
    smelt/popped_chorus_fruit
    smelt/brown_glazed_terracotta
)

for task in "${tasks[@]}"; do
    env_config="$task"

    # Evaluate
    num_iterations=3
    for ((i = 0; i < num_iterations; i++)); do
        python mcabench/evaluate/evaluate.py \
            --agent-mode "rt2" \
            --workers $workers \
            --env-config $env_config \
            --max-frames $max_frames \
            --temperature $temperature \
            --model-path $model_name_or_path \
            --demo "" \
            --video-main-fold "/publicX/lmy/evaluate/$model_local_path" \
            --base-url "$base_url" \
            --history-num $history_num \
            --instruction-type $instruction_type \
            --action-chunk-len $action_chunk_len \
            --record True \
            #--verbos True \
            


        if [[ $? -eq 0 ]]; then
            echo "第 $i 次迭代中的 Python 脚本执行成功，退出循环。"
            break
        fi
        if [[ $i -lt $((num_iterations - 1)) ]]; then
            echo "等待 10 秒..."
            sleep 10
        fi
    done
done 